### ISSUE TITLE
Is this per tab or per browser?

### ISSUE THREAD

**Issue by migig** [dillbyrne/toggle_js#5]
If it's for the whole browser, would be useful to have it work on a per-tab basis.

Lots of sites I visit keep on running loads of stuff even when I'm not using that tab. I'd like to freeze those tabs by clicking a menu button for each tab, so they stop hogging my system's resources.

**Comment by dillbyrne** [comment]
It uses a global browser preference. It is meant to be a quick toggle of JS . If you require more fine grained controls NoScript is the tool for the job.
